### ISSUE TITLE
upload image

### ISSUE THREAD

**Issue by littlewin-wang** [littlewin-wang/vue-images#1]
![images](https://cloud.githubusercontent.com/assets/14028075/21972475/d92b8490-dbf4-11e6-8d18-8225ce738a4b.gif)

**Comment by littlewin-wang** [comment]
![images](https://cloud.githubusercontent.com/assets/14028075/22059135/9a633f74-dda6-11e6-8314-3b745801b4e1.gif)

**Comment by sotaan** [comment]
do you mean lazyload images?

**Comment by littlewin-wang** [comment]
not plan yet...
just done all features

ps. this issue is used for upload gif for README.md
