### ISSUE TITLE
Problem with displaying images array

### ISSUE THREAD

**Issue by patpaskoch** [littlewin-wang/vue-images#10]
the gallery and everything work just fine but I have trouble displaying the array of images. In your demo, you have a multi row gallery. In my case, the images don't break onto a new line if reaching the end of the parent div.

![image](https://cloud.githubusercontent.com/assets/4086365/26052885/1eee2850-3967-11e7-9a93-bb77fad75491.png)

**Comment by littlewin-wang** [comment]
Check the version, this modification added in 1.0.8.
If problem still there, pls show me the styles setting of  the parent div.

**Comment by patpaskoch** [comment]
worked with updating npmv. 1.0.9
