### ISSUE TITLE
Question about events

### ISSUE THREAD

**Issue by patpaskoch** [littlewin-wang/vue-images#11]
Hi I got everything going, I really like your work. I just wanted to add an optional delete btn to every image to trigger ajax requests to a server to delete the image. I added an id to every image in the array to spec. However I can trigger the delete event in gallery.vue and catch it in lightbox.vue but I cant emit it to the root instance.

my fork https://github.com/patpaskoch/vue-images

**Comment by littlewin-wang** [comment]
I tried and find that the name of event in the root file should not use CamelCase.
For eg, `deleteImage` does not work, but `delete` just work fine.

check commit in https://github.com/littlewin-wang/vue-images/commit/73ea39dd2be95b9a26c2febc1784aa308331a74e
