### ISSUE TITLE
this library automatically rotates images 90 degrees to make them fit? how to disable this behavior?

### ISSUE THREAD

**Issue by vesper8** [littlewin-wang/vue-images#12]
I've noticed that this library rotates some pictures 90 degrees to make them fit nicely.. however it's doing this to pictures that should not be rotated.. how do I disable this behaviour? Is this being done via the css? I can't figure out what's doing it or why it's doing it

thanks!

**Comment by littlewin-wang** [comment]
Could u pls show a demo to me ? I have not meet this prob...
