### ISSUE TITLE
How to display the caption below to the image, not in lightbox

### ISSUE THREAD

**Issue by pathirajendra** [littlewin-wang/vue-images#15]
I am using the npm to display the images and slideshow, can you plz help to display the caption to the image like the screenshot. 
![screenshot from 2017-06-10 17-48-09](https://user-images.githubusercontent.com/18664729/27002672-06325068-4e05-11e7-8f80-f5d10d016e20.png)

Thanks in advance

**Comment by littlewin-wang** [comment]
A little css code can do this. Try to modify the position define in 
https://github.com/littlewin-wang/vue-images/blob/master/src/components/fancybox.vue#L201
