### ISSUE TITLE
Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by BeiKeJieDeLiuLangMao** [littlewin-wang/vue-images#16]
Code:
```
 import vueImages from 'vue-images'
 components: {
      vueImages: vueImages
    }
<vue-images :images="images"></vue-images>
```
Version:vue-images@1.0.9
Then:
Cannot read property 'length' of undefined"

**Comment by JohnYunhan** [comment]
You should change the "images" to "imgs"

**Comment by JohnYunhan** [comment]
`new Vue({
  el: '#demo',
  data () {
    return {
      images: [
        {
          imageUrl: 'https://images.unsplash.com/photo-1454991727061-be514eae86f7?dpr=2&auto=format&w=1024',
          caption: '<a href="#">Photo by 1</a>'
        },
        {
          imageUrl: 'https://images.unsplash.com/photo-1455717974081-0436a066bb96?dpr=2&auto=format&w=1024',
          caption: 'Photo by 2'
        },
        {
          imageUrl: 'https://images.unsplash.com/photo-1460899960812-f6ee1ecaf117?dpr=2&auto=format&w=1024',
          caption: 'Photo by 3'
        }
      ],
      modalclose: true,
      keyinput: true,
      mousescroll: true,
      showclosebutton: true,
      showcaption: true,
      imagecountseparator: 'of',
      showimagecount: true,
      showthumbnails: true
    }
  },
  components: {
    vueImages: vueImages.default
  }
})`

**Comment by JohnYunhan** [comment]
new Vue({
  el: '#demo',
  data () {
    return {
      images: [
        {
              imageUrl: 'https://images.unsplash.com/photo-1454991727061-be514eae86f7?
                               dpr=2&auto=format&w=1024',
              caption: '<a href="#">Photo by 1</a>'
        },
        {
              imageUrl: 'https://images.unsplash.com/photo-1455717974081-0436a066bb96?
                              dpr=2&auto=format&w=1024',
              caption: 'Photo by 2'
        },
        {
          imageUrl: 'https://images.unsplash.com/photo-1460899960812-f6ee1ecaf117?dpr=2&auto=format&w=1024',
          caption: 'Photo by 3'
        }
      ],
      modalclose: true,
      keyinput: true,
      mousescroll: true,
      showclosebutton: true,
      showcaption: true,
      imagecountseparator: 'of',
      showimagecount: true,
      showthumbnails: true
    }
  },
  components: {
    vueImages: vueImages.default
  }
})

**Comment by BeiKeJieDeLiuLangMao** [comment]
oh, thanks
