### ISSUE TITLE
使用最新的vue-cli来构建，无法使用

### ISSUE THREAD

**Issue by rossroma** [littlewin-wang/vue-images#3]
vue-cli版本为2.8.1
webpack版本为2.2.1

运行 npm run dev 后，
控制台报错
```
 ERROR  Failed to compile with 1 errors

This dependency was not found in node_modules:

* vue-images

Did you forget to run npm install --save for it?
> Listening at http://localhost:8081
```
我重新安装了vue-images后，问题依旧，而且查看node-modules里也确实存在vue-images

**Comment by littlewin-wang** [comment]
Hi，之前发布npm的时候改了下webpack配置，你可以研究下webpack
或者等我俩天修改，最近稍微有点忙...

**Comment by maisnamraju** [comment]
Having the same issues, would appreciate some feedback on how to configure this.

**Comment by littlewin-wang** [comment]
@maisnamraju  @rossroma 
Now I seprate the entry js file of 'npm run dev' & 'npm run build'
You can use the dev mode now.

**Comment by lbausch** [comment]
Doesn't work, same error message. I end up with the following files in `node_modules/vue-images`:

```
├── dist
│   ├── vue-images.css
│   └── vue-images.js
├── LICENSE
├── package.json
└── README.md
```

**Comment by littlewin-wang** [comment]
@lbausch 
I tried again and no mistake...
