### ISSUE TITLE
import 进来表示Can't resolve

### ISSUE THREAD

**Issue by kukujbb** [littlewin-wang/vue-images#6]
已经用npm下载了

**Comment by Sinord** [comment]
You need to add non-compiled .vue files to npm package for opportunity to ES6 import

**Comment by vrajroham** [comment]
Previously I was getting same error. Resolved using above snippet. But now following error occurs.

`did you register the component correctly? For recursive components, make sure to provide the "name" option. `

**Comment by Sinord** [comment]
Just use default declaration of component
`components: { vueImages },`
instead
`components: { vueImages: vueImages.default },`
