### ISSUE TITLE
ERROR！！！

### ISSUE THREAD

**Issue by kevinYMY** [littlewin-wang/vue-images#7]
[Vue warn]: Unknown custom element: <vue-images> - did you register the component correctly? For recursive components, make sure to provide the "name" option. (found in root instance)            
 ----------------- vue.min.js : 2611

照你的例子用ES6的方式导入，就报这个错，

**Comment by kevinYMY** [comment]
原来是我Vue的版本太低了，sorry！

**Comment by vrajroham** [comment]
Getting same error

**Comment by littlewin-wang** [comment]
update vue version to 2.1.0 and try again
