### ISSUE TITLE
how to change css so it appears in a normal float/grid, and clickable link in caption?

### ISSUE THREAD

**Issue by vesper8** [littlewin-wang/vue-images#9]
Is it possible to add html in the caption? Right now it just prints the html. How do have a clickable link as part of caption?

And also, right now the css causes a very long row.. I have over 100 images. How can I change the css so that it appears in a normal float grid ?

Thanks for this library otherwise! very useful and easy to use!

**Comment by littlewin-wang** [comment]
Hi
1. I add html parser for the caption.
2. Add 'flex-wrap: wrap' to the gallery. If you want add some customized styles to the images gallery, you can change the stylus code in the '[gallery.vue](https://github.com/littlewin-wang/vue-images/blob/master/src/components/gallery.vue)'.

And thanks for your encouragement BTW. :smile:
